# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_test', '0003_auto_20170618_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='code_test.Genre'),
        ),
    ]
